[env:esp32s3cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

; --- PSRAM : le module Freenove (N8R8) utilise de la PSRAM Octal-SPI ---
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -Ilib/abdallah-xx-project-1_inferencing/src
    -Ilib/abdallah-xx-project-1_inferencing/src/edge-impulse-sdk

lib_ldf_mode = deep+
lib_archive = no

build_src_filter = 
    +<*>
    +<../lib/abdallah-xx-project-1_inferencing/src/edge-impulse-sdk>
    +<../lib/abdallah-xx-project-1_inferencing/src/tflite-model>
    +<../lib/abdallah-xx-project-1_inferencing/src/model-parameters>