[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

monitor_speed = 115200

lib_ldf_mode = deep+ 

lib_archive = no

build_flags = 
    -Ilib/abdallah-xx-project-1_inferencing/src
    -Ilib/abdallah-xx-project-1_inferencing/src/edge-impulse-sdk

build_src_filter = 
    +<*>
    +<../lib/abdallah-xx-project-1_inferencing/src/edge-impulse-sdk>
    +<../lib/abdallah-xx-project-1_inferencing/src/tflite-model>
    +<../lib/abdallah-xx-project-1_inferencing/src/model-parameters>